apiVersion: v1
kind: Secret
metadata:
  name: foodify-secrets
type: Opaque
stringData:
  # Database / Infra
  POSTGRES_DB: foodify
  POSTGRES_USER: foodify
  POSTGRES_PASSWORD: foodify
  SPRING_DATASOURCE_USERNAME: foodify
  SPRING_DATASOURCE_PASSWORD: foodify
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/foodify
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  JWT_SECRET: change_me_jwt_secret_at_least_32_characters_long
  JWT_REFRESH_SECRET: change_me_jwt_refresh_secret_at_least_32_characters

  # Konnect configuration
  KONNECT_ENVIRONMENT: "sandbox"

  KONNECT_SANDBOX_API_KEY: "67f7aa541cf716b1828ae5dd:QJBHtTZnSqcTlrksKL"
  KONNECT_SANDBOX_WALLET_ID: "67f7aa541cf716b1828ae5e5"
  KONNECT_SANDBOX_WEBHOOK_URL: "https://apiv3.foodifytn.app/api/payments/konnect/webhook"

  KONNECT_PRODUCTION_API_KEY: ""
  KONNECT_PRODUCTION_WALLET_ID: ""
  KONNECT_PRODUCTION_WEBHOOK_URL: "https://apiv3.foodifytn.app/api/payments/konnect/webhook"

  # Expo
  EXPO_ACCESS_TOKEN: "n9T9QLlCHmK7aKx_Ii9gLhyDRn9yr0M3aMQHdzgC"

  # Cloudflare Images
  CLOUDFLARE_IMAGES_ACCOUNT_ID: "eaaa30184708e2bf58d2969c580428ed"
  CLOUDFLARE_IMAGES_API_TOKEN: "LCoiLCPkBpdMpXrn6U_sLK63Ox-ZCE0wLIuIs6JV"
  MAIL_SMTP_HOST: "smtp.zoho.com"
  MAIL_SMTP_PORT: "587"
  MAIL_SMTP_USERNAME: "no-reply@foodifytn.app"
  MAIL_SMTP_PASSWORD: "gl-4xddR"
  MAIL_SMTP_FROM: "no-reply@foodifytn.app"
  MAIL_SMTP_SUBJECT: "Your Foodify verification code"

