apiVersion: v1
kind: Secret
metadata:
  name: foodify-secrets
type: Opaque
stringData:
  # TODO: set real values here before applying
  POSTGRES_DB: foodify
  POSTGRES_USER: foodify
  POSTGRES_PASSWORD: foodify
  SPRING_DATASOURCE_USERNAME: foodify
  SPRING_DATASOURCE_PASSWORD: foodify
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/foodify
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  JWT_SECRET: change_me_jwt_secret
