apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodify-server-app
  labels:
    app: foodify-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodify-server-app
  template:
    metadata:
      labels:
        app: foodify-server-app
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres..."
              until nc -z postgres 5432; do
                echo "  still waiting for postgres"
                sleep 2
              done
              echo "Postgres is up."

              echo "Waiting for Kafka..."
              until nc -z kafka-broker 9092; do
                echo "  still waiting for kafka"
                sleep 2
              done
              echo "Kafka is up."

              echo "Waiting for Redis..."
              until nc -z redis 6379; do
                echo "  still waiting for redis"
                sleep 2
              done
              echo "Redis is up. Starting app."
      containers:
        - name: foodify-server-app
          image: ghcr.io/mortadha-nefzi/foodify-server:build-26
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            # DB
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: SPRING_DATASOURCE_PASSWORD

            # Redis
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: SPRING_REDIS_PORT

            # Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS

            # JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: JWT_SECRET
            
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: JWT_REFRESH_SECRET

            # Konnect
            - name: KONNECT_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_ENVIRONMENT

            - name: KONNECT_SANDBOX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_SANDBOX_API_KEY
            - name: KONNECT_SANDBOX_WALLET_ID
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_SANDBOX_WALLET_ID
            - name: KONNECT_SANDBOX_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_SANDBOX_WEBHOOK_URL

            - name: KONNECT_PRODUCTION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_PRODUCTION_API_KEY
            - name: KONNECT_PRODUCTION_WALLET_ID
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_PRODUCTION_WALLET_ID
            - name: KONNECT_PRODUCTION_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: KONNECT_PRODUCTION_WEBHOOK_URL

            # Expo
            - name: EXPO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: EXPO_ACCESS_TOKEN

            # Cloudflare Images
            - name: CLOUDFLARE_IMAGES_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: CLOUDFLARE_IMAGES_ACCOUNT_ID
            - name: CLOUDFLARE_IMAGES_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: foodify-secrets
                  key: CLOUDFLARE_IMAGES_API_TOKEN

            # Timezone
            - name: TZ
              value: "Africa/Tunis"

          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
