apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodify-server-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - apiv3.foodifytn.app
      secretName: apiv3-tls
  rules:
    - host: apiv3.foodifytn.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: foodify-server-service
                port:
                  number: 80
