spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - apiv3.foodifytn.app
      secretName: apiv3-tls      # name can be anything; this is just clearer
  rules:
    - host: apiv3.foodifytn.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: foodify-server-service
                port:
                  number: 80
